apiVersion: batch/v1
kind: CronJob
metadata:
  name: netbox-ssot
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: netbox-ssot
              image: ghcr.io/src-doo/netbox-ssot:v1.11.2
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              volumeMounts:
                - name: netbox-ssot-secret
                  mountPath: /app/config.yaml
                  subPath: config.yaml
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                runAsUser: 10001
                runAsGroup: 10001
                seccompProfile:
                  type: RuntimeDefault
          volumes:
            - name: netbox-ssot-secret
              secret:
                secretName: netbox-ssot-secret
          restartPolicy: Never
